apiVersion: batch/v1
kind: Job
metadata:
  name: calci-job
spec:
  template:
    spec:
      containers:
      - name: calci-job
        image: yash5090/calci:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
