apiVersion: apps/v1
kind: Deployment
metadata:
  name: calci-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: calci
  template:
    metadata:
      labels:
        app: calci
    spec:
      containers:
        - name: calci
          image: yash5090/calci:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
